{% set version = "1.2.0" %}

package:
  name: appmode
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/appmode/appmode-{{ version }}.tar.gz
  sha256: 6d2c690f8ac255e614019ea38a156ee145de815c0359a90606dfdeb53dd9a1b5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - nbclassic >=1
  run:
    - python >={{ python_min }}
    - nbclassic >=1

test:
  requires:
    - python {{ python_min }}
  imports:
    - appmode

about:
  home: https://github.com/oschuett/appmode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Jupyter extensions that turns notebooks into web applications.'

extra:
  recipe-maintainers:
    - oschuett
