{% set version = "0.5.0" %}

package:
  name: appmode
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/appmode/appmode-{{ version }}.tar.gz
  sha256: 61942e7c5be13f0bf4295e17ece84d2d7e7a0b2a4ba63c81d07445e4afb91c44

build:
  number: 1002
  # noarch: python # suffers from https://github.com/conda/conda-build/issues/2357
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - notebook >=5
  run:
    - python
    - notebook >=5

test:
  imports:
    - appmode

about:
  home: https://github.com/oschuett/appmode
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A Jupyter extensions that turns notebooks into web applications.'

extra:
  recipe-maintainers:
    - oschuett
