{% set version = "1.0.0" %}

package:
  name: appmode
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/appmode/appmode-{{ version }}.tar.gz
  sha256: 120c2151caab90679f3f530cda2f4971ea859d62c8ae3767421f3689d81554d9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - nbclassic >=1
  run:
    - python >=3.7
    - nbclassic >=1

test:
  imports:
    - appmode

about:
  home: https://github.com/oschuett/appmode
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Jupyter extensions that turns notebooks into web applications.'

extra:
  recipe-maintainers:
    - oschuett
