appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CM572VVSe/aGr7ZBwqZXmYsrPAp1lVNawPXMujpRujal0RAVkZd7pAc1SvCl2GE4n6MIqD8SbsMAlQpNjG9zmpwX0V2dWxErde/nwUifDqceE4SbeuYGqOrOGMg+Pc5zTbozC0lZG+5dY9Z7MvtIa8Jx8IQGFCy8MimrDVQ5q8KDJWDRSa5iqOA5OmmPnEN18KXNM3dICPFN1PypQPTDxb8BjImz8kmnz/wX6yxdVtQu5TY5PurVpK06T043DtzrpprhICaAnRKWutE2IJA+Ud4TN81XVGDsbJclhyCQRTHCm1SGqMVPibNXz2a1ObeyhLAJHtiThiM4/3ut0e2AKnluCHKUz2bnTNS4b0ylOk6HH2Lu5CxdReJSo2F8IGjb2u2M0zCD8EUmBWRbxdfHy80TE9Tml+T/SODM+yC6gQxcIngUfoNC10ZyUHxzpKXWuMtEGX42gkNbWFAI9QLjPWxwQDwEz8Sz40iP9IaY2tlb19tO0nwt9QxmTUQnHgqWsNUo3ICf7uff0yknjYSY2/qF78v70ueioeXDpIR4QW2jsdNSOo7bxizN66/HRzx4ZGonfK3s6KtcOwx9v/ouHaQ3cwfP/OImRVx02q9TdTHR794TwJZxh0pqgO6PMjSsZq2KWkwsYkd19iawO/IPG/4PQOjn2F3h9uoFH1VYCF8=}
provider:
  win: azure
conda_forge_output_validation: false
